<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\VDT.Core.DependencyInjection.Tests.Targets.References\VDT.Core.DependencyInjection.Tests.Targets.References.csproj" />
	</ItemGroup>

</Project>
